### PR TITLE
Conditionally modify path to allow compilation

### PR DESCRIPTION
**Pull request by gcapes**
Our university MATLAB licence results in us only running compiled MATLAB on our HPC system. As such I've been working out how to compile this toolbox for a user. This PR is what I've come up with.

I still get two occurences of the warning below
> Warning: While loading an object of class 'orientation':
Invalid default value for property 'CS' in class 'orientation':
SWITCH expression must be a scalar or a character vector. 
> In matlab.depfun.internal.MatFileInspector/getSymbols (line 58)
  In matlab.depfun.internal.MwFileInspector/analyzeSymbol (line 34)
  In matlab.depfun.internal.Completion/findDependentFiles (line 1399)
  In matlab.depfun.internal.Completion/computeDependencies (line 262)
  In matlab.depfun.internal.Completion/computePartsList (line 2052)
  In matlab.depfun.internal.Completion/requirements (line 2461)
  In matlab.depfun.internal.requirements (line 205)
  In matlab.depfun.internal.mcc_call_requirements (line 9) 

These might or might not present room for improvement in the MTEX code. I'm not sure how to investigate them further, but perhaps someone familiar with the code can take a look?

### CODE REVIEW

**Comment by ralfHielscher** [comment]
Thank you for sharing this. I do not understand the warnings :(

**Comment by cbetoIng** [comment]
Hi,

as already discussed here [#847](https://github.com/mtex-toolbox/mtex/discussions/847#discussion-3262705), compiling the toolbox using Matlab itself seems to be a problem.

Could you please explain how to compile source code using your compile-mtex script? As I'm not used to command line tools I'm having a hard time here...

Regards,
Christian

**Comment by gcapes** [comment]
Sorry it looks like I missed a second variable that needs to be set. I've updated the script comments in #969.
The script `compile-mtex` should be made executable and run from a Bash shell like this:
`compile-mtex your-script-which-uses-mtex.m`

**Comment by cbetoIng** [comment]
Thank you for the clarification! I got the application to compile but now several runtime errors occur due to `feval()` not finding the desired m-files. This is somehow not surprising, as they are not explicitly called and hence not included in the compilation. 
When I call the EBSD.load function with parameter 'interface' set to 'ctf' the error occurs here:
`  ebsd{k} = feval(['loadEBSD_',char(interface)],...
    fname{k},options{:},'InfoLevel',~is3d,varargin{:});   %#ok<AGROW>`

One work around for me is to use [Matlab Pragmas](https://www.mathworks.com/help/compiler/function.html) and tell the compiler to include the respective files in the build process. Here `%#function loadEBSD_ctf` was added to the beginning of the load-function to resolve the error...

Is there any other more elegant way besides including all m-files in the build process?

Regards,
Christian

**Comment by gcapes** [comment]
If you look at the last line of `mtex-include`, I've 'forced' it to include all the data files by using the `-a` option. If the m-files that aren't being found are all in the same place you could try adding another similar line I guess. Otherwise I can't think of a better work around.

**Comment by cbetoIng** [comment]
Wouldn't changing `'-I', 'LOCALPATH\mtex\mtex-5.6.1',...` to `'-a', 'LOCALPATH\mtex\mtex-5.6.1',...` include all files? By adding the `-a` option the data-folder, only the example data is added to the build, or am I wrong here?  

When `'-a', 'LOCALPATH\mtex\mtex-5.6.1` is used other issues occur due to synthax errors in some m-files...but this can be remedied quite easily...

**Comment by gcapes** [comment]
From memory I think that `-I` tells `mcc` where to look for m-files, but it assesses which it needs to compile into the archive. `-a` adds recursively regardless of what is needed so you might get a compiled archive larger than needed - the intended use is for data rather than m-files.
https://uk.mathworks.com/help/compiler/mcc.html

But I guess `feval` messes up this process.

It *might* be the case that it compiles faster if you use the pragmas to indicate which m-files should be included rather than compiling with the `-a` option.

You'll probably just have to experiment with it. I am not an MTEX user so I'm not really any sort of authority on this, and I don't think the MTEX authors dabble with compiling their toolbox.

**Comment by ralfHielscher** [comment]
Wouldn't it be possible for you to avoid using `EBSD.load` but instead call `loadEBSD_interfaceName` directly?

Ralf.

**Comment by cbetoIng** [comment]
Yes, this would also solve my problem. As gcapes already said: some experimentation helps and slowly but surely I'm working my way through it.

Regards,
Christian

**Pull request merged**
