### PR TITLE
Update plotAngleDistribution.m

### PR DESCRIPTION
**Pull request by nicholasbyres**
Hi Ralph,

is this the correct way to go about helping? I'm not really a coder so Github, coding etc. is all new to me! You mentioned help with correcting the English of which I feel I could contribute. 

Best,
Nick

### CODE REVIEW

**Comment by ralfHielscher** [comment]
Hi Nick,

yes this is the way to go :+1: 

Thank you very much.

Ralf.

**Comment by lfgmorales** [comment]
Hi Nick


You can go here


https://mtex-toolbox.github.io/Documentation.html



and follow the instructions



The idea is that you use your own script with a little bit of information regarding why/when those calculations are important, adding a little bit of background information


After you complete that, Ralf transforms part of the text in html file, and the code lines stay as code, so people can easily copy and paste them in their scritps


give it a try, we can clean up the code afterwards



cheers



Luiz





Luiz F. G. Morales
ScopeM & Structural Geology and Tectonics Group
ETH Zürich
________________________________

**Comment by lfgmorales** [comment]
Ups, sorry, I think you managed to do it properly, I missed part of the email



cheers



Luiz





Luiz F. G. Morales
ScopeM & Structural Geology and Tectonics Group
ETH Zürich
________________________________

**Comment by nicholasbyres** [comment]
No worries! It’s useful to understand how this all works anyway.

Best,
Nick

**Pull request merged**
